- name: Connect to hosts
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Fetch Credentials
      set_fact:
        ansible_user: "{{ lookup('cyberark.conjur.conjur_variable', conjur_subdomain_path ~ '/username', validate_certs=false) }}"
        ansible_host: "{{ lookup('cyberark.conjur.conjur_variable', conjur_subdomain_path ~ '/address', validate_certs=false) }}"
        ansible_ssh_private_key_file: "{{ lookup('cyberark.conjur.conjur_variable', conjur_subdomain_path ~ '/password', validate_certs=false , as_file=true) }}"
      delegate_to: localhost
      
  tasks:
    - name: Verify Credentials
      debug:
        msg: "Host: {{ ansible_host }} | User: {{ ansible_user }} | Target IP: {{ ansible_host }} | Key Path: {{ ansible_ssh_private_key_file }}"
