---
- name: Connect to hosts using Conjur secrets
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Resolve connection details locally
      set_fact:
        ansible_user: "{{ lookup('cyberark.conjur.conjur_variable', conjur_path_prefix ~ '/' ~ inventory_hostname ~ conjur_path_suffix ~ '/username', validate_certs=false) }}"
        ansible_host: "{{ lookup('cyberark.conjur.conjur_variable', conjur_path_prefix ~ '/' ~ inventory_hostname ~ conjur_path_suffix ~ '/address', validate_certs=false) }}"
        ansible_ssh_private_key_file: "{{ lookup('cyberark.conjur.conjur_variable', conjur_path_prefix ~ '/' ~ inventory_hostname ~ conjur_path_suffix ~ '/password', validate_certs=false, as_file=true) }}"
      delegate_to: localhost

  tasks:
    - name: Test SSH connection
      ping:
